name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          CI: "true"    # IMPORTANT: tell the app to use dummy model/scaler
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # NEW: Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # NEW: Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/churn-api:latest .

       # NEW: Push Docker image
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/churn-api:latest
